# Generated by Django 3.1 on 2020-09-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COVID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalStats', models.TextField()),
                ('countries', models.TextField()),
            ],
        ),
    ]
